#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/seu-net/seu-net"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/seu-net/seu-net &
	fi
	echo "seu-net is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/seu-net/seu-net"` 2>/dev/null
	echo "seu-net exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}